### ISSUE TITLE
Dealing with wrong input (e.g., format)

### ISSUE THREAD

**Issue by danielpeintner** [eclipse-thingweb/domus-tdd-api#11]
I know that the format keyword should be limited to  `array` or `collection`.

Hence calling 
http://plugfest.thingweb.io:8081/things?format=collection
or
http://plugfest.thingweb.io:8081/things?format=array
works.

Anyhow, providing faulty input causes internal server failure.
http://plugfest.thingweb.io:8081/things?format=foo

produces

![grafik](https://github.com/user-attachments/assets/c87b4650-b7cb-413e-a7ea-e1b7e80121af)

EDIT: I think it should provide a better error message.

**Comment by wiresio** [comment]
Fixed by: https://github.com/eclipse-thingweb/domus-tdd-api/pull/12
